apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: experiments
  source:
    path: manifests/charts/gateways/istio-egress
    repoURL: https://github.com/istio/istio.git
    targetRevision: 1.9.0
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
